env:
  es6: true
  node: true

extends: 'airbnb-base'

globals:
  assert: true
  browser: true
  expect: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  comma-dangle:
    - 'error'
    - arrays: 'always-multiline'
      objects: 'always-multiline'
      imports: 'never'
      exports: 'never'
      functions: 'ignore'
  global-require: 'off'
  indent:
    - 'error'
    - 4
    - SwitchCase: 1
  max-len:
    - 'error'
    - 80
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - 'error'
    - newIsCap: true
      capIsNewExceptions:
        - 'Given'
        - 'When'
        - 'Then'
  require-jsdoc:
    - 'error'
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict: 'off'
  valid-jsdoc:
    - 'error'
    - requireReturn: false
      matchDescription: '.+'
